8282209: G1: Use synchronous concurrent marking for the code cache
openjdk/loom pull request #102
Opened 2022-03-15 15:33 UTC by lkorinth

This fix removes collect_for_codecache(), and uses collect() directly instead. This has the advantage that the g1 code path can be run concurrently using a concurrent mark instead of a full gc.

2022-03-15 15:37 UTC, fisk approved these changes
Looks good. Ship it!

2022-03-15 15:54 UTC, tschatzl requested changes

2022-03-15 15:54 UTC, tschatzl commented on src/hotspot/share/gc/g1/g1FullCollector.cpp
> +    CodeCache::start_marking_cycle();
Please add a helper method for this copy&paste in `G1CollectedHeap`. Something like `start_codecache_marking_cycle_if_inactive` (not perfect) or similar.

2022-03-15 15:54 UTC, tschatzl commented on src/hotspot/share/gc/g1/g1Policy.cpp
>        // A concurrent start must be young only GC, so the collector state
The comment needs an update.
to

2022-03-15 20:28 UTC, tschatzl approved these changes
Lgtm. Thanks.

2022-03-16 07:56 UTC, fisk approved these changes
Looks good. Ship it!

2022-03-16 16:29 UTC, fisk commented
/sponsor

2022-03-16 16:31 UTC, closed without merging